### ISSUE TITLE
crypto errors

### ISSUE THREAD

**Issue by urherenow** [aarch64-switch-rs/cargo-nx#13]
as of the latest commits, emuiibo can no longer be built with this. It throws a bunch of crypto errors such as 
"instruction requires aes" 
or 
"instruction requires: sha2"

I don't know if it's a bug in cargo-nx or if emuiibo needs to be updated, but I'm thinking the problems came from build.rs changes https://github.com/XorTroll/emuiibo/issues/229#issuecomment-1444985921

**Comment by XorTroll** [comment]
I'm aware of this, the tier 3 target we now use apparently didn't include crypto support
This issue isn't related to cargo-nx per se tho
