### ISSUE TITLE
Move to using the tier 3 target

### ISSUE THREAD

**Issue by GnomedDev** [aarch64-switch-rs/cargo-nx#6]
It seems like https://github.com/rust-lang/rust/pull/88991 has merged and there is now a target for the Nintendo Switch, `aarch64-nintendo-switch-freestanding`. It seems like this project should be using this target now and has intended to in the past once it is merged in https://github.com/aarch64-switch-rs/cargo-nx/blob/f6bd1f4a15e38d6ad900701394745fe92be8ccb9/src/build.rs#L29

**Comment by XorTroll** [comment]
Done on last commit
